### ISSUE TITLE
Sparkline flickers/disappears when megafilter is used on page

### ISSUE THREAD

**Issue by LorenzoSapora** [dcasia/nova-mega-filter#29]
I think I can see it flicker on when I refresh the page, but it's so brief, it's hard to tell.

Using dummy data and called from the database.

`Sparkline::make('Trend')->data('0,0,0,0,1,0,0,0,0')`.

It reappears whenever a column is removed.

**Comment by milewski** [comment]
Nova doesn't have a nice api to refresh the resource table, so the way I do it is by finding the resource table component on the tree and calling a method directly on it to refetch the resources.. Sadly that method also does more than just refresh the table but also fetch cards, filters... Etc... This is what causes the cards to flash, because they are indeed being destroyed and reconstructed everytime you toggle a column

**Comment by LorenzoSapora** [comment]
Interesting. How would that effect the sparkline, though. As it should just be an SVG pulling from a data set. If I set the sparkline column to ->permanent(), and refresh the page, it doesn't show the contents (90% of the time it's totally blank, 10% of the time it flashes for a fraction of a second, then disappears again). The only way to see the sparkline is to change a column/filter, thus forcing a refresh.

It could be a nova bug, but I've not hit that issue on sparklines on other pages with pseudo-refreshing (filterable metric cards, for example) actions.
