### ISSUE TITLE
Feature: column::make() act like normal Nova field, which has many functions like displayUsing()

### ISSUE THREAD

**Issue by phoenixg** [dcasia/nova-mega-filter#34]

**Comment by milewski** [comment]
Whats the use case?

**Comment by phoenixg** [comment]
Column::make('My Field Name', 'my_field')->function() {
                    switch ($this->status) {
                        case Model::STATUS_UNDO:
                        case Model::STATUS_PROCESS:
                            return 'handling';
                        case Model::STATUS_SUCCEED:
                            return 'success';
                        default:
                            return 'unknown';
                    }
                });

**Comment by milewski** [comment]
This package is used as `card` and card doesn't have `$this->resource` available, that means your `$this->status` would always be null, the only way for you getting that value would be by resolving the model from the request like this:

```
$model = request(NovaRequest::class)->->findModelOrFail()
$model->status
```

However, this would only work on the details page, because the resource ID is present on the URL, but on index page where is the only place that `nova-mega-filter` is supported it wouldnt work
